# Basic Site Settings
title: "Chanon Ketkarn"
email: "chanon.ketkarn@gmail.com"
description: "Portfolio and Blog of Chanon Ketkarn"
author: "Chanon Ketkarn"
baseurl: "" # Leave empty unless your site is in a subdirectory
url: "https://yourgithubusername.github.io"

# Social Links
github_username: "yourgithubusername"
linkedin_username: "your-linkedin-profile"
scholar_userid: "" # If applicable
twitter_username: "" # If applicable

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Publications"
    url: "/publications/"
  - title: "Projects"
    url: "/projects/"
  - title: "Experience"
    url: "/experience/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Contact"
    url: "/contact/"

# Experience (for use in the `experience.md` page)
experience:
  - title: "Software Engineering Intern"
    company: "Teibto"
    duration: "July 2024 - September 2024"
    description: |
      - Developed Suitelet scripts for Oracle NetSuite.
      - Created a custom document printing system for invoices and inventory.
  - title: "Workshop Instructor"
    company: "Bangpakok Witthayakom School"
    duration: "July 2023 - August 2023"
    description: |
      - Taught Python fundamentals and data science libraries.
      - Conducted workshops on Decision Trees, Linear Regression, and PowerBI.
  - title: "Thailand Esports Athlete"
    company: "Team Thailand"
    duration: "June 2019 - Dec 2019"
    description: |
      - Won a gold medal in Arena of Valor at the 30th SEA Games.

# Education
education:
  - school: "King Mongkut’s University of Technology Thonburi (KMUTT)"
    degree: "Bachelor of Engineering in Computer Engineering"
    duration: "2021 - Expected 2025"

# Skills
skills:
  programming_languages: ["Python", "C", "JAVA", "HTML", "CSS", "JavaScript"]

# Theme Settings
theme: jekyll-theme-minimal
